<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class Guru
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_user
 * @property string $nomor_pegawai
 * @property string $telepon
 * @property string $alamat
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Pengajar[] $pengajars
 * @property \App\Models\User $user
 */
class Guru extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'guru';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user', 'nomor_pegawai', 'telepon', 'alamat'
        ,'foto','tempat_lahir','tanggal_lahir','tahun_mengajar'
        ,'status_kepegawaian','pendidikan_terakhir'
    ];

    /**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function kelas()
	{
		return $this->hasOne(
            // Model
            'App\Models\Kelas',
            // Foreign key
            'wali_kelas',
            // Local key
            'id');
	}

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function absen()
    {
        return $this->hasMany(
        // Model
            'App\Models\Absen',
            // Foreign key
            'pengajar',
            // Local key
            'id');
    }

    /**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function user()
	{
		return $this->belongsTo(
			// Model
			'App\Models\User',
			// Foreign key
			'user',
			// Other key
			'id'
		);
	}
}
