<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class Kela
 * @package App\Models
 *
 * @property integer $id
 * @property string $kelas
 * @property string $jurusan
 * @property string $pararel
 * @property string $kode_kelas
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Jadwal[] $jadwals
 * @property \App\Models\Siswa[] $siswas
 */
class Kelas extends Model
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'kelas';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'wali_kelas','kelas','keterangan',
    ];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function guru()
	{
		return $this->hasOne(
			// Model
			'App\Models\Guru',
			// Foreign key
			'id',
			// Local key
			'wali_kelas'
		);
	}

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function siswa()
    {
        return $this->hasMany(
        // Model
            'App\Models\Siswa',
            // Foreign key
            'kelas',
            // Local key
            'id'
        );
    }

    public function siswa_select($options = 1)
    {
        if($options < 5 && $options > 0){
            return Siswa::all()->where('kelas',$this->kelas)->where('status',$options);
        }else{
            return Siswa::all()->where('kelas',$this->kelas)->where('status',1);
        }
    }


}
