<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * No description found in the table comment.
 *
 * Class Siswa
 * @package App\Models
 *
 * @property integer $id
 * @property string $nomor_pelajar
 * @property string $nama
 * @property string $telepon
 * @property string $alamat
 * @property integer $id_kelas
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Absen[] $absens
 * @property \App\Models\Kela $kela
 */
class Siswa extends Model 
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'siswa';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nomor_pelajar', 'nama','alamat','kelas','status', 'foto',
        "jenis_kelamin","tempat_lahir","tanggal_lahir","kebangsaan",'telepon','nomor_akta_kelahiran',
        "agama","anak_ke","status_anak","jumlah_saudara","siswa_pindahan_baru","ukuran_sepatu"

    ];

    /**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function absen()
	{
		return $this->hasMany(
			// Model
			'App\Models\Absen',
			// Foreign key
			'siswa',
			// Local key
			'id'
		);
	}

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function absen_weekly()
    {
        return DB::table('absen')->selectRaw('CONCAT(YEAR(absen_buka), \'/\', WEEK(absen_buka)), siswa')
            ->where('siswa',$this->id)
            ->groupBy('CONCAT(YEAR(absen_buka), \'/\', WEEK(absen_buka))')->get();

    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function wali()
    {
        return $this->hasMany(
        // Model
            'App\Models\WaliSiswa',
            // Foreign key
            'siswa',
            // Local key
            'id'
        );
    }
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function status()
    {
        return $this->belongsTo(
        // Model
            'App\Models\StatusSiswa',
            // Foreign key
            'status',
            // Local key
            'id'
        );
    }

    /**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function kelas()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Kelas',
			// Foreign key
			'kelas',
			// Other key
			'id'
		);
	}



}
